-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "DP-2", mode = "3840x2160@60.00", position = "0x32", scale = 2.00 })
hl.monitor({ output = "DP-3", mode = "3840x2160@60.00", position = "1920x32", scale = 2.00 })
